language: scala

scala:
  - 2.12.8

jdk:
  - openjdk8

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_install:
  - "test -z \"$encrypted_36594ebbab48_key\" || (openssl aes-256-cbc -K $encrypted_36594ebbab48_key -iv $encrypted_36594ebbab48_iv -in project/secrets.tar.enc -out project/secrets.tar -d && tar -xf project/secrets.tar -C project)"

stages:
  - name: lint
  - name: test
  - name: publish
    if: branch = master AND type = push

jobs:
  include:
    - stage: lint
      name: "Check source code formatting"
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
    - &test
      stage: test
      name: "Build and test for Scala 2.12"
      before_script: gpg --import project/ci.asc
      script: sbt ++$TRAVIS_SCALA_VERSION test package packageSrc publishLocal
    - <<: *test
      scala: 2.11.12
      name: "Build and test for Scala 2.11"
    - <<: *test
      scala: 2.13.0-M5
      name: "Build and test for Scala 2.13"
    - &publish
      stage: publish
      name: "Publish for Scala 2.12"
      before_script: gpg --import project/ci.asc
      script: sbt ++$TRAVIS_SCALA_VERSION sonatypeOpenIfNotSnapshot publish sonatypeReleaseIfNotSnapshot
    - <<: *publish
      scala: 2.11.12
      name: "Publish for Scala 2.11"
    - <<: *publish
      scala: 2.13.0-M5
      name: "Publish for Scala 2.13"

env:
  global:
    - secure: "SAeiUGiijqZ1jqYxIZJOShPK1HbZ+fZrpl9EbzZqlKo+N1n38lQSr9LxTjOappHEGG1Rw7CDag5m5kufSR7SiaE5WrOYBGppDwqXPYyJOign4Jy65VBoYOmVsYn5y9GB81hc6H7RETwDRV+3+gXmWbUCd7JniM91LUp7Nj2y7+RU2HXzW0K2E7mQSypJUtk76TXRNSmJBYsp7oBPS8WaLQclD0XGeKdjzzFQh+DjpoxuHzbs4E6CT6dTooBw9sY76/31sOsuiiJrexbmlGtudkPqdu2Lek942Y5045b4hvJLQmL4KwDGpb5xTq/H6c+secdAtC16EG/+uNWdp+JjR3X3V0olCh/pmFkncs/nHeSxWqz8P2jFUbdxGoZ0V79b0sC1qYv3W4ntdtvVkhcJU36YKSd3BP8Nnm0NlslqQgCOBVwXd9LFa2zt86Z/uFEG7a91g9Hv77RVilYtP60zmrTnRLPnnL5hUlr1ys+Q+LGinazP9dIWM7sCqGb3jQ75+HNfPSUjNaZiMOkC8eQMvypQUD0NW2GgzsozIna9EQdb3nvghhs2jz4jyvLnRruzcra0y9CU9SqYv/WDOc/9fuiHLw3PUWcSfQA2ftrwvMNUQHry9mHFoOjHe1BbtfpwqfCnReVjgubMGRLw/tXW1H/s3kLiVKSiscBiQpUfSoE="
    - secure: "DD8X4Yq0wrgN0lKdGhwXm/F3UOow01o5MKgqBlA8pKWqcurWWscrJ+CNU/XpxoNXEAtUBdNOHzv1VXjdjLtk6SbQMLE244BSFCXbb8xfox5ZfF64xxsRUf8RWkt9Q2qc/nWHC+qTdv8Q1oWvrE3UE0gV9Qrk3SCzb5/fTDJJ0ssfusuWPOBYkKRI8oIF7EdH4QRG47KhlsaXgy7r8T5uqpNUvWSQm/PayzgVZPDza2jOJOh1ATqViOiToak2Mvx3IBfmdbnlgtQG5lesAea5ltECLAzoYxVrKh+QRuvgpugw0u0sRlp25ec6zO8wCpc7jJnWTsVaqMvSQcyMN718xQXuI74aE5xzrfANgRB4o7X6tIAVJ0va5VKeJ+rIC37w+nOCCcc6ypkLNhh34Q1BYhhLdaZoqRsAzEHtZ6x1gVJYsj2A7DZdaLz4cNh9yt+zcBSrG2cYd2etp3b8+uf1dArnNlCF4nCOu+Ev/lWVCJ/4V+VMeRGHsFj8ys/k8PcE7oYOtsa1H9xBeRZmA86TfAKIWiB9jDd12cVI2frNrvvw69kQ4btmjI0H0oYM+3vKWhh3LJmeZvpnu8G7S6O3FdtMRFHGWwqctgSO6W8ova0KCuUT703MEEWi4AG9wFxkGD3bBfW+EAqtT8Rbzj6i6JTY3N62ZQ940PJwgvrkbcQ="
