language: scala

scala:
  - 2.12.8

jdk:
  - openjdk8

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_install:
  - "test -z \"$encrypted_36594ebbab48_key\" || (openssl aes-256-cbc -K $encrypted_36594ebbab48_key -iv $encrypted_36594ebbab48_iv -in project/secrets.asc.enc -out - -d | tar -C project -xf -)"

stages:
  - name: lint
  - name: test
  - name: publish
    if: branch = master AND type = push

jobs:
  include:
    - stage: lint
      name: "Check source code formatting"
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
    - &test
      stage: test
      name: "Build and test for Scala 2.12"
      before_script: gpg --import project/ci.asc
      script: sbt ++$TRAVIS_SCALA_VERSION test package packageSrc publishLocal
    - <<: *test
      scala: 2.11.12
      name: "Build and test for Scala 2.11"
    - <<: *test
      scala: 2.13.0-M5
      name: "Build and test for Scala 2.13"
    - &publish
      stage: publish
      name: "Publish for Scala 2.12"
      before_script: gpg --import project/ci.asc
      script: sbt ++$TRAVIS_SCALA_VERSION publish
    - <<: *publish
      scala: 2.11.12
      name: "Publish for Scala 2.11"
    - <<: *publish
      scala: 2.13.0-M5
      name: "Publish for Scala 2.13"
